$(document).ready(function(){
  if(sessionStorage.doll=="true"||sessionStorage.cabKey=="true"){
      $('.doll').hide();
  }
  $('.doll').click(function(){
      sessionStorage.doll="true";
      $('.doll').hide();
    });
})
